
# The microcontroller
MCU := atmega328p
# The clock speed in Hz.
CLOCK := 16000000

# The location of the AVR-LIBC headers
AVR_LIBC_HEADERS := /usr/avr/include

CC  := clang
LLC := llc
MC  := llvm-mc

CFLAGS := -O --target=avr -mmcu=$(MCU) -DF_CPU=$(CLOCK) \
	      -isystem $(AVR_LIBC_HEADERS)

LLCFLAGS := -march=avr -mcpu=$(MCU)

MCFLAGS := -arch=avr -mcpu=$(MCU)



